services:
  mysql:
    image: mysql:8.4.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: work-management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
