version: 3

includes:
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend

tasks:
  default:
    desc: 使用可能なタスクを一覧表示
    cmds:
      - task --list --sort none
    silent: true

  up-db:
    desc: データベースを起動
    cmds:
      - docker compose up -d mysql
    silent: true
