//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "break_sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub work_session_id: i32,
    pub start_time: DateTimeUtc,
    pub end_time: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::work_sessions::Entity",
        from = "Column::WorkSessionId",
        to = "super::work_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WorkSessions,
}

impl Related<super::work_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
