//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::break_sessions::Entity as BreakSessions;
pub use super::projects::Entity as Projects;
pub use super::work_sessions::Entity as WorkSessions;
